server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /daryl
    username: admin
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual