server:
  port: 18084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        #id唯一标识，自定义
        - id: user-service-root
          #路由的服务地址
          #uri: http://localhost:18081 #写死了  不好

          #lb协议表示从eureka注册中心获取服务请求地址
          #user-provider访问的服务名称
          #路由地址如果通过lb协议加服务名称时，会自动使用负载均衡访问对应服务
          uri: lb://user-provider
          #路由拦截的地址配置（断言）
          predicates:
            #- Path=/user/**
            - Path=/**
          filters:
            #请求地址添加路径前缀过滤器
            #- PrefixPath=/user
            # 去除路径前缀过滤器
            - StripPrefix=1
      default-filters:
        - AddResponseHeader=password,Daryl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka